country: EU27 # country to show in charts (write "all" to run all countries)

# Years selection
year:
  first: 2011 # earliest year covered
  last: 2021 # latest year covered

# Actions to do
actions:
  download: False  # True: download raw data, False: use existing data
  clear: False # True clears existing charts, False: only replace the ones generated
  context: False # Generate context data (Part 1)
  industry_GVA_final: True # Run the decomposition of the final energy consumption in the industry sector, based on GVA
  industry_GVA_primary: False # Run the decomposition of the primary energy consumption in the industry sector, based on GVA
  economy_emp_final: False # Run the decomposition of the final energy consumption in the different economy sector, based on employment
  household_final: False # Run the decomposition of the final energy consumption in the residential sector
  transport_final: False # Run the decomposition of the final energy consumption in the industry sector, based on VKM


